[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "nmpc_examples"
version = "0.1.0"
description = "Prototyping data structures for rolling-horizon dynamic optimization."
authors = [
    { name = "Robert Parker", email = "rparker1@andrew.cmu.edu" },
]
license = { text = "BSD-3" }

[tool.setuptools.packages.find]
include = ["nmpc_examples*"]
